# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3EtS3EATju8z5WcBC4kiJdeCqKN4lau

## Password Checker Project
"""

#password Conditions
#min 8 char,digit,Uappercase,lowercase,special char

import re

def check_password_strength(password):

  if len(password)<8:
    return "Weak: Password must have 8 Char"

  if not any(char.isdigit() for char in password):
    return "Weak: Password must conatin a digit"

  if not any(char.isupper() for char in password):
    return "Weak: Password must have a uppercase letter in it"

  if not any(char.islower() for char in password):
    return "Weak: Password must have a lower char"

  if not re.search(r"[!@#$%^&*()+=<>?]",password):
    return "Weak: Password must have a special char in it"

  return "Strong: Your password is secured!"

def password_checker():

  while True:
    passwordCheck =input("Enter your password (or type 'exit' to quite):")

    if passwordCheck.lower() == "exit":
      print("thank you for using this tool")
      break

    result= check_password_strength(passwordCheck)
    print(result)


 #run the password checker
if __name__ =="__main__":
  password_checker()







